spring:
  application:
    name: rag-shield-core
  ai:
    vectorstore:
      pinecone:
        index-name: rag-shield-index
        api-key: ${PINECONE_API_KEY:mock-key}
        environment: ${PINECONE_ENVIRONMENT:us-east-1}
        project-id: ${PINECONE_PROJECT_ID:mock-project-id}
